### PR TITLE
Add option for className of DropdownItem

### PR DESCRIPTION
**Pull request by briman0094**
There's an option to specify the `className` of the Dropdown itself, so it would be nice (and make sense) to be able to specify it for the DropdownItems as well. This PR adds such functionality. I'll update the documentation after creating the PR and commit it to the same branch.

I successfully ran the unit test, although it seemed to start a Karma server and hang indefinitely. I didn't get any warnings about test failures beforehand, so I can only assume the tests passed.

### CODE REVIEW

**Comment by briman0094** [comment]
Strike the part about documentation, I didn't see that it's auto-generated! Let me know if any changes are needed.

**Comment by briman0094** [comment]
Ugh, tests failed on CI. I'm not sure how to run them locally. Flow doesn't work on WSL, the tests seem to be Linux-only, and Karma doesn't seem to be working with a remote browser.

**Comment by briman0094** [comment]
Sorry for all the commits to try and fix these unit tests. I don't have a graphical Linux environment in which I can test these before pushing.

**Comment by briman0094** [comment]
So, I tested this and it works as intended now. I'm waiting on a Linux image to install so that I can actually run unit tests while developing, but if somebody else is able to fix the unit tests before I can, that would be great. I don't think the items are getting populated to the dropdown before the assert is made on the number of matching elements. I tested this in a real world scenario and the class name option is properly handled.

**Comment by briman0094** [comment]
Good news! I got my Linux image working and finally got the tests passing.

**Comment by yuku-t** [comment]
@briman0094 Thanks for the patch. It looks good to me. Could you squash these commits into a single commit?

**Comment by briman0094** [comment]
Done!

**Comment by yuku-t** [comment]
0.15.0 was released

**Pull request merged**
